name: Formatting Check

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  formatting_check:
    runs-on: ubuntu-22.04
    container: wpilib/roborio-cross-ubuntu:2025-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y wget lsb-release software-properties-common
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18
          sudo apt-get install -y clang-format-18
          sudo ln -sf /usr/bin/clang-format-18 /usr/bin/clang-format

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Install Roborio Toolchain
        run: ./gradlew installRoborioToolchain

      - name: Spotless Check
        run: ./gradlew spotlessCheck -PfromCI  -PrunningSpotlessCpp
